/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef worker_CONSTANTS_H
#define worker_CONSTANTS_H

#include "worker_types.h"

namespace freebird
{
class workerConstants {
public:
    workerConstants();
};

extern const workerConstants g_worker_constants;

} // namespace freebird

#endif
